apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/PetPortal
  type: udm.Application
  children:
  - name: "2.0-90"
    type: udm.DeploymentPackage
    children:
    - name: petclinic
      type: jee.War
      scanPlaceholders: true
      placeholders:
      - TITLE
      file: !file "PetClinic/target/PetClinic.war"
    - name: petclinic-backend
      type: jee.War
      file: !file "PetClinic-Backend/target/PetClinic-Backend.war"
    - name: logger
      type: app.Logger
      placeholders:
      - log.RootLevel
      - log.FilePath
      file: !file "dar/logger"
    - name: sql
      type: sql.SqlScripts
      file: !file "dar/sql"
    - name: petDataSource
      type: jee.DataSourceSpec
      jndiName: jdbc/petds
    - name: testPage
      type: smoketest.HttpRequestTest
      url: '{{tests2.ExecutedHttpRequestTest.url}}'
      expectedResponseText: '{{TITLE}}'